### ISSUE TITLE
molecular structure and structural representation are not arrangements

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#243]
both classes are subclasses of arrangement with structure as an intermediate. 

Arrangement is defined as a plan, manner or method for making, doing, achieving or organizing.
I understand that an arrangement is a specification on how to do something by an agent. (making, doing, archieving and organizing are active).

Structure is defined as arrangement and organization of interrelated elements in a material object of system.
This seems to limit it to a specification on how things are organized.

This is certainly true by things that are made, but what about natural things. They are not unless you are a creationalist.

Structure is descriptive or defines things. A structure defines common spatial, topological, mereological properties that are shared by material objects or systems. To achieve such as structure can be a objective of an active making or doing, but it is not necessarily so. A chemist looks at the molecular structure and then think on how to synthesize the substance, but the structure is independent of the chemist. 

A molecular structure describes the topological and spatial positions (to avoid the word arrangement) of the atoms in a molecule.
It does so at a certain level of precision and from a specific perspective. The relative spatial position of atoms is not fixed, a molecule bends and twists, and even the topology of bonds can change constantly in time, it is only simple model of real atoms and molecules.

Structural representation is a way that molecular structures which do exist are represented in texts, diagrams, pictures. The are manifestations of the abstract expression of the molecular structure and share common rules and patterns, on how certain aspects are represented. These rules are specifications, e.g. the specification of the MDL Mol format, or the specification of SMILES, but the mol file or SMILES string is not.

A structural representation is also not a subclass of structure. It is a representation of structure.

Stereochemistry is a structure. In most cases it is also a molecular structure, but the way stereochemistry is defined in IDMP it is not necessarily so because the list in IDMP includes "racemic", which is a mereological property of a mixture, and depends on the stereochemistry of its constituents. The stereochemistry of the molecule is the 3d spatial and topological structure.
The stereochemistry can also be represented different ways, so one can define a stereochemical representation along with structural representation, but both are often represented together.

**Comment by ElisaKendall** [comment]
@tw-osthus I think this was "mostly" addressed with the changes made via pull request #274. Please take a look, though to make sure that the changes are sufficient. Some of the notes in your explanation, above, could be added as notes to the ontology and there are also a few cases where we have properties, such as for SMILES but not classes, so we should decide if any additional changes are needed.

**Comment by ElisaKendall** [comment]
To finalize this, we need to add a note to structure saying that it may include "A structure defines common spatial, topological, mereological properties that are shared by material objects or systems." Structure is intrinsic to the thing it describes or defines.

We also need a note on molecular structure stating: A molecular structure describes the topological and spatial positions (to avoid the word arrangement) of the atoms in a molecule.
It does so at a certain level of precision and from a specific perspective. The relative spatial position of atoms is not fixed, a molecule bends and twists, and even the topology of bonds can change constantly in time, it is only simple model of real atoms and molecules." or similar.

We should also add a note to stereochemistry with respect to "Stereochemistry is a structure. In most cases it is also a molecular structure, but the way stereochemistry is defined in IDMP it is not necessarily so because the list in IDMP includes "racemic", which is a mereological property of a mixture, and depends on the stereochemistry of its constituents. The stereochemistry of the molecule is the 3d spatial and topological structure.
The stereochemistry can also be represented different ways, so one can define a stereochemical representation along with structural representation, but both are often represented together."  We should discuss with the ISO IDMP WG whether certain values for stereochemistry impacts our representation of substance. If substance is a classifier, then we can use the set of values given as the values for stereochemistry. Otherwise we should split these between stereochemistry of single substances vs. mixtures, and possibly suggest other ways of representing this. For example, racemic only applies to mixtures, not to all substances.

**Comment by ElisaKendall** [comment]
One approach might be to create two subclasses of Stereochemistry - one for molecular structure and the other for bulk material stereochemistry, and then split the set of individuals appropriately.

**Comment by ElisaKendall** [comment]
We also need definitions for some of the individuals where there were not clear definitions in the IDMP standards.

**Comment by ElisaKendall** [comment]
This was addressed via pull request #279. A new issue, #284, has been added to cover a few missing notes.
