### ISSUE TITLE
Empty English short name for World resource

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#319]
Resource https://www.omg.org/spec/LCC/Countries/UN-M49-RegionCodes/World has a null value for property https://www.omg.org/spec/LCC/Countries/CountryRepresentation/hasEnglishShortName.

**Comment by ElisaKendall** [comment]
@mereolog Nice catch - no idea how that happened. We can update it in our version, but it really needs to be fixed in LCC. I'll raise a parallel issue in the LCC Jira on the OMG site.

**Comment by ElisaKendall** [comment]
@mereolog This is now issue number LCC13-7 on the OMG server at https://issues.omg.org/browse/LCC13-7. That Jira is limited to OMG members, but it is there. So I recommend that we close this to LCC13-7, which may not be addressed for several months, FYI due to process, but I'll fix it and move the revision over once the voting on the ballot that includes the fix passes.
