### ISSUE TITLE
substance identifier does not identify physical substances, but classifies them

### ISSUE THREAD

**Issue by tw-osthus** [edmcouncil/idmp#376]
idmp-sub:SubstanceIdentifier has the following restriction:
``` 
cmns-id:identifies some 
    ('idmp-sub:physical substance' or idmp-sub:substance)
```

This should be replaced with

``` 
cmns-id:identifies some idmp-sub:substance
cmns-cls:classifies some 'idmp-sub:physical substance'

```

The substance identifier does not identify the stuff only the type of stuff.

**Comment by ElisaKendall** [comment]
@merelog @tw-osthus I understand the issue that Thomas has raised, though I think in the case of substance and 'physical substance' we are still talking about a kind of substance rather than a very specific amount of that substance that one can 'touch'. The substance identifier does not yet exist, in fact, but WHO will be developing it over the next few years. Thus is is possible that the changes they make will require other modifications to the ontology.

I think we should close this with no change, in other words, and defer until WHO defines an internationally unique identifier for every substance known today as well as those that have yet to be invented.

**Comment by tw-osthus** [comment]
Using `<substance identifier> identifies <physical substance>` only  makes sense if the physical substance is the whole of all stuff being classified by the substance type.

For practicall purposes, the substance identifier identifying portions of physical substances will rather be an instance of a batch/sample identifier. 

As the definition is not wrong, just too broad IMHO, we can leave it as is.
