### ISSUE TITLE
Names for substances - concepts and examples differences

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#384]
At the level of concepts/classes we require that a [substance](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Substance) [has substance name](https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/hasSubstanceName) some [substance name](https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/SubstanceName):
https://github.com/edmcouncil/idmp/blob/487882fcdbacf78b74aa1c3c415da9af8e189c0a/ISO/ISO11238-Substances.rdf#L3082-L3088

However for most instances of [substance](https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/Substance) (as of as of [487882f](https://github.com/edmcouncil/idmp/commit/487882fcdbacf78b74aa1c3c415da9af8e189c0a)) we use the inverse of the superproperty of [has substance name](https://spec.edmcouncil.org/idmp/ontology/ISO/ISO11238-Substances/hasSubstanceName) instead: [is name of](https://www.omg.org/spec/Commons/Designators/isNameOf). That is to say, for a substance name we say that it [is name of](https://www.omg.org/spec/Commons/Designators/isNameOf) some substance, e.g., [terlipressin official name](https://spec.edmcouncil.org/idmp/ontology/EXT/Examples/TerlipressinExample/TerlipressinOfficialName) [is name of](https://spec.edmcouncil.org/idmp/ontology?query=https%3A%2F%2Fwww.omg.org%2Fspec%2FCommons%2FDesignators%2FisNameOf) [terlipressin](https://spec.edmcouncil.org/idmp/ontology/EXT/Examples/TerlipressinExample/Terlipressin).

Given the open world assumption, this is technically correct, but it also introduces an unnecessary divergence between the concepts/classes and their examples.

Of course there is no harm in using the inverse, but either the examples should use a subproperty of [is name of](https://www.omg.org/spec/Commons/Designators/isNameOf), which is yet to be created, or the above restriction should use [has name](https://www.omg.org/spec/Commons/Designators/hasName).

**Comment by ElisaKendall** [comment]
@mereolog There are some additional examples coming that relate to various kinds of names - will be investigating over the coming weeks as to whether or not the hasName side of the equation should be an explicit restriction. Typically I recommend modeling the inverse side because these substances have a gazillion names, and to avoid ambiguity or wrong answers it is the molecular structure that defines them, but will check the specifications again and confirm that we do not need the restriction to be as strong. I think the examples need to be corrected, in other words, not the ontology.
