### ISSUE TITLE
Use of incomparable datatypes

### ISSUE THREAD

**Issue by mereolog** [edmcouncil/idmp#565]
https://www.w3.org/TR/xmlschema11-2/#order reads:
"For purposes of this specification, the value spaces of primitive datatypes are disjoint, even in cases where the abstractions they represent might be thought of as having values in common.  In the order relations defined in this specification, values from different value spaces are [·incomparable·](https://www.w3.org/TR/xmlschema11-2/#dt-incomparable).  For example, the numbers two and three are values in both the decimal datatype and the float datatype.  In the order relation defined here, the two in the decimal datatype is not less than the three in the float datatype; the two values are incomparable."
See also https://www.w3.org/TR/xmlschema11-2/#built-in-primitive-datatypes

For this reason the following datatype inheritance facts are inconsistent:
dataproperty1 |  dataproperty2 |  range1 |  range2
--|--|--|--
https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO21090-HarmonizedDatatypes/hasIntegerValue |  https://www.omg.org/spec/Commons/QuantitiesAndUnits/hasNumericValue |  xsd:integer |  xsd:decimal
https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO21090-HarmonizedDatatypes/hasLevelInHierarchy |  https://www.omg.org/spec/Commons/QuantitiesAndUnits/hasNumericValue |  xsd:nonNegativeInteger |  xsd:decimal

**Comment by tw-osthus** [comment]
float and decimal are disjoint but integer and decimal are not. integer is a subtype of decimal and nonNegativeInteger is a subtype of integer

see https://www.w3.org/TR/xmlschema-2/#integer


> 3.3.13 integer
> [Definition:]   integer is [·derived·](https://www.w3.org/TR/xmlschema-2/#dt-derived) from [decimal](https://www.w3.org/TR/xmlschema-2/#decimal) by fixing the value of [·fractionDigits·](https://www.w3.org/TR/xmlschema-2/#dt-fractionDigits) to be 0and disallowing the trailing decimal point. This results in the standard mathematical concept of the integer numbers. The [·value space·](https://www.w3.org/TR/xmlschema-2/#dt-value-space) of integer is the infinite set {...,-2,-1,0,1,2,...}. The [·base type·](https://www.w3.org/TR/xmlschema-2/#dt-basetype) of integer is [decimal](https://www.w3.org/TR/xmlschema-2/#decimal).

**Comment by mereolog** [comment]
The fact that one type is derived from the other does not imply that the value space of one is included in the value space of the other.

https://www.w3.org/TR/xmlschema-2/#equal reads explicitly that
"the [·value space·](https://www.w3.org/TR/xmlschema-2/#dt-value-space)s of all [·primitive·](https://www.w3.org/TR/xmlschema-2/#dt-primitive) datatypes are disjoint (they do not share any values)"
By https://www.w3.org/TR/xmlschema-2/#built-in-primitive-datatypes xsd:integer and xsd:decimal are primitive.

Also Fact++ 1.6.5 finds the following ontology inconsistent exactly because of this:

```
@prefix : <http://www.semanticweb.org/pawel.garbacz/ontologies/2024/3/datatype_test/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.semanticweb.org/pawel.garbacz/ontologies/2024/3/datatype_test/> .

<http://www.semanticweb.org/pawel.garbacz/ontologies/2024/3/datatype_test> rdf:type owl:Ontology .

:p1 rdf:type owl:DatatypeProperty ;
    rdfs:range xsd:decimal .

:a1 rdf:type owl:NamedIndividual ;
    :p1 "1"^^xsd:integer .
```

![image](https://github.com/edmcouncil/idmp/assets/11171688/1217f08d-e652-42b9-8461-e09779824805)

**Comment by tw-osthus** [comment]
integer is not a primitive datatype

Some reasoners do not handle datatypes well

________________________________
Von: Pawel Garbacz ***@***.***>
Gesendet: Montag, 8. April 2024 17:42
An: edmcouncil/idmp ***@***.***>
Cc: Thomas Weber ***@***.***>; Assign ***@***.***>
Betreff: Re: [edmcouncil/idmp] Use of incomparable datatypes (Issue #565)


The fact that one type is derived from the other does not imply that the value space of one is included in the value space of the other.

https://www.w3.org/TR/xmlschema-2/#equal reads explicitly that
"the ·value space·<https://www.w3.org/TR/xmlschema-2/#dt-value-space>s of all ·primitive·<https://www.w3.org/TR/xmlschema-2/#dt-primitive> datatypes are disjoint (they do not share any values)"
By https://www.w3.org/TR/xmlschema-2/#built-in-primitive-datatypes xsd:integer and xsd:decimal are primitive.

Also Fact++ 1.6.5 finds the following ontology inconsistent exactly because of this:

@prefix : <http://www.semanticweb.org/pawel.garbacz/ontologies/2024/3/datatype_test/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://www.semanticweb.org/pawel.garbacz/ontologies/2024/3/datatype_test/> .

<http://www.semanticweb.org/pawel.garbacz/ontologies/2024/3/datatype_test> rdf:type owl:Ontology .

:p1 rdf:type owl:DatatypeProperty ;
    rdfs:range xsd:decimal .

:a1 rdf:type owl:NamedIndividual ;
    :p1 "1"^^xsd:integer .


image.png (view on web)<https://github.com/edmcouncil/idmp/assets/11171688/1217f08d-e652-42b9-8461-e09779824805>
